"""
Email Delivery Module
=======================
Sends the generated PDF report to designated recipients via Gmail SMTP
using smtplib. Includes retry logic and clear error logging.
"""

import smtplib
import ssl
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from pathlib import Path

from config.settings import Config
from config.logger import get_logger

log = get_logger(__name__)


def build_email_body(kpis: dict, week_start, week_end) -> str:
    """Plain-text summary used as the email body (PDF has full detail)."""
    return f"""\
Hello Team,

Please find attached the {Config.COMPANY_NAME} Weekly Business Report
for the period {week_start.strftime('%d %b %Y')} – {week_end.strftime('%d %b %Y')}.

QUICK SUMMARY
---------------------------------------------
Revenue Generated      : Rs.{kpis['total_revenue']:,.0f}
New Projects Started   : {kpis['new_projects_count']}
Projects Completed     : {kpis['completed_count']}
Overdue Tasks          : {kpis['overdue_count']}
Invoices Paid          : {kpis['invoices_paid_count']} (Rs.{kpis['invoices_paid_amount']:,.0f})
Top Performer          : {kpis['top_performer']} ({kpis['top_performer_count']} tasks)
Invoice Collection Rate: {kpis['collection_rate']:.1f}%
Team Utilization       : {kpis['utilization_rate']:.1f}%
---------------------------------------------

The full report — including charts, project breakdowns, overdue task
details, and recommendations — is attached as a PDF.

This is an automated message generated by the {Config.COMPANY_NAME}
Weekly Reporting System. Please do not reply directly to this email.

Best regards,
{Config.COMPANY_NAME} Automated Reporting System
"""


def send_email_with_attachment(pdf_path: str, kpis: dict, week_start, week_end,
                                max_retries: int = 3) -> bool:
    """
    Sends the PDF report via Gmail SMTP.
    Retries up to `max_retries` times on transient failures.
    Returns True on success, False on permanent failure.
    """
    Config.validate()

    subject = Config.EMAIL_SUBJECT_TEMPLATE.format(
        company=Config.COMPANY_NAME,
        week_start=week_start.strftime("%d %b %Y"),
        week_end=week_end.strftime("%d %b %Y"),
    )
    body = build_email_body(kpis, week_start, week_end)

    msg = MIMEMultipart()
    msg["From"]    = Config.SMTP_EMAIL
    msg["To"]      = ", ".join(Config.EMAIL_RECIPIENTS)
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    pdf_file = Path(pdf_path)
    if not pdf_file.exists():
        log.error(f"PDF file not found at {pdf_path}; cannot send email.")
        return False

    with open(pdf_file, "rb") as f:
        part = MIMEApplication(f.read(), _subtype="pdf")
        part.add_header("Content-Disposition", "attachment", filename=pdf_file.name)
        msg.attach(part)

    attempt = 0
    while attempt < max_retries:
        attempt += 1
        try:
            log.info(f"Sending email (attempt {attempt}/{max_retries}) to {Config.EMAIL_RECIPIENTS}")
            context = ssl.create_default_context()
            with smtplib.SMTP(Config.SMTP_SERVER, Config.SMTP_PORT, timeout=30) as server:
                server.starttls(context=context)
                server.login(Config.SMTP_EMAIL, Config.SMTP_PASSWORD)
                server.sendmail(Config.SMTP_EMAIL, Config.EMAIL_RECIPIENTS, msg.as_string())

            log.info(f"Email sent successfully to {len(Config.EMAIL_RECIPIENTS)} recipient(s).")
            return True

        except smtplib.SMTPAuthenticationError as e:
            log.error(
                f"SMTP authentication failed: {e}. "
                f"Make sure SMTP_PASSWORD is a Gmail App Password, not your regular password."
            )
            return False  # no point retrying auth errors

        except (smtplib.SMTPConnectError, smtplib.SMTPServerDisconnected, TimeoutError) as e:
            log.warning(f"Transient SMTP error on attempt {attempt}: {e}")
            if attempt < max_retries:
                wait = 5 * attempt
                log.info(f"Retrying in {wait} seconds...")
                time.sleep(wait)
            else:
                log.error("Max retries reached. Email delivery failed.")
                return False

        except Exception as e:
            log.error(f"Unexpected error while sending email: {e}")
            return False

    return False
